[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
contract = { path = "../contract" }

tokio.workspace = true
ethers.workspace = true
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
axum-macros.workspace = true
